[package]
name = 'WebGestaltR'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'WebGestaltR'

[dependencies]
extendr-api = '0.6.0'
ndarray = "0.15.6"
rustc-hash = "1.1.0"
webgestalt_lib = {git = "https://github.com/bzhanglab/webgestalt_rust.git"}
